CREATE TABLE settings (
    id SERIAL PRIMARY KEY,
    organization_id INTEGER NOT NULL,
    theme_color VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)