on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      deployments: write
    name: Publish project to Demo env of Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8.6.2
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd vim-canvas-demo-app-react && pnpm install
      - name: Build react app
        run: cd vim-canvas-demo-app-react && pnpm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: vim-canvas-demo-app-demo
          directory: dist
          workingDirectory: vim-canvas-demo-app-react
